name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYY-MM-DD
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          config: .github/buildkitd.toml
      - uses: docker/build-push-action@v2
        with:
          push: false
          # platforms: "linux/amd64,linux/arm64,linux/386,linux/arm/v7,linux/arm/v6"
          tags: "tiangolo/nginx-rtmp:latest,tiangolo/nginx-rtmp:latest-${{ steps.current-time.outputs.formattedTime }}"
