name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          config: .github/buildkitd.toml
      - run: |
          docker buildx build --platform \
          "linux/amd64,linux/arm64,linux/386,linux/arm/v7,linux/arm/v6" .
